#!/usr/bin/with-contenv sh
dumps(){
    DB=$1
    PREFIX=$2
    SUFIX=$3
    echo "> "$DB
    ERROR=0
    mkdir -p /var/lib/mysql-backup/$PREFIX$DB$SUFIX/
    tables=$(mysql -NBA -u root -p$ROOT_PASSWORD -D $DB -e 'show tables')
    for tab in $tables;
    do
        echo -n "   > $tab"
        mysqldump -uroot -p$ROOT_PASSWORD $DB $tab > /var/lib/mysql-backup/$PREFIX$DB$SUFIX/$tab.sql
        if [ "$?" -eq 0 ]
        then
            echo " ........ OK"
        else
            echo " !!!!!!!! NOK"
            ERROR=1
            echo $tab >> /var/lib/mysql-backup/$PREFIX$DB$SUFIX/status.log
            echo $LOG >> /var/lib/mysql-backup/$PREFIX$DB$SUFIX/status.log
            sleep 15
        fi
    done
    
    echo $ERROR  > /var/lib/mysql-backup/$PREFIX$DB$SUFIX/status
    
}

process(){
    
    DATE=$(date +%H)
    dumps $1 "temp-" "-$DATE"
    TMPPATH="temp-"$1"-$DATE"
    if [ "$(cat /var/lib/mysql-backup/$TMPPATH/status)" = "0"];
    then
        rm -r /var/lib/mysql-backup/$1-*
        mv /var/lib/mysql-backup/$TMPPATH /var/lib/mysql-backup/$1-$DATE
    fi   
}


next(){
    echo "> Get Next Site"
    COUNTER=$(($COUNTER + 1))
}

is_db_enabled(){
    NAME="DB_"$COUNTER"_NAME"
    DB_NAME=$(eval 'echo $'$NAME)
    if [ -z "$DB_NAME" ];
    then
        return 1
    fi
    
    return 0
}


COUNTER=0
while [ 1 -eq 1 ];
do
    if ! is_db_enabled;
    then
        break
    fi
    process $DB_NAME
    next
done