version: '3'

services:

  mariadb:
    image: dotriver/mariadb
    environment:
      - ROOT_PASSWORD=password
      - DB_0_NAME=db0
      - DB_0_PASSWORD=passworddb0
    ports:
      - 3306:3306
      - 8080:80
    volumes:
      - mariadb-data:/var/lib/mysql/
      - mariadb-config:/etc/mysql/
    networks:
      default:
    
volumes:
    mariadb-data:
    mariadb-config:
