#!/usr/bin/with-contenv sh

backup(){
    echo "> "$1
    mv /var/lib/mysql-backup/$1.6 /var/lib/mysql-backup/$1.7 > /dev/null 2>&1
    mv /var/lib/mysql-backup/$1.5 /var/lib/mysql-backup/$1.6 > /dev/null 2>&1
    mv /var/lib/mysql-backup/$1.4 /var/lib/mysql-backup/$1.5 > /dev/null 2>&1
    mv /var/lib/mysql-backup/$1.3 /var/lib/mysql-backup/$1.4 > /dev/null 2>&1
    mv /var/lib/mysql-backup/$1.2 /var/lib/mysql-backup/$1.3 > /dev/null 2>&1
    mv /var/lib/mysql-backup/$1.1 /var/lib/mysql-backup/$1.2 > /dev/null 2>&1
    mv /var/lib/mysql-backup/$1 /var/lib/mysql-backup/$1.1 > /dev/null 2>&1
}

dump(){
    ERROR=0
    mkdir -p /var/lib/mysql-backup/$1/
    tables=$(mysql -NBA -u root -p$ROOT_PASSWORD -D $1 -e 'show tables')
    for tab in $tables;
    do
        echo -n "   > $tab"
        LOG=$(mysqldump -uroot -p$ROOT_PASSWORD $1 $tab > /var/lib/mysql-backup/$1/$tab.sql > /dev/null 2>&1)
        if [ "$?" -eq 0 ]
        then
            echo " ........ OK"
        else
            echo " !!!!!!!! NOK"
            ERROR=1
            echo "\n\n" >> /var/lib/mysql-backup/$1/status.log
            echo $tab >> /var/lib/mysql-backup/$1/status.log
            echo $LOG >> /var/lib/mysql-backup/$1/status.log
        fi
    done
    
    echo $ERROR  > /var/lib/mysql-backup/$1/status
    
}


next(){
    echo "> Get Next Site"
    COUNTER=$(($COUNTER + 1))
}

is_db_enabled(){
    NAME="DB_"$COUNTER"_NAME"
    DB_NAME=$(eval 'echo $'$NAME)
    if [ -z "$DB_NAME" ];
    then
        return 1
    fi
    
    return 0
}


COUNTER=0
while [ 1 -eq 1 ];
do
    if ! is_db_enabled;
    then
        break
    fi
    backup $DB_NAME
    dump $DB_NAME
    next
done