#!/usr/bin/with-contenv sh

TMP_PATH=/root/
PERSIT_PATH=/var/lib/mysql-backup/

dumps(){
    echo -n "> "$DB_NAME
    ERROR=0
    mysqldump -uroot -p$ROOT_PASSWORD $DB_NAME > $TMP_PATH/$DB_NAME.sql
    if [ "$?" -eq 0 ]
    then
        echo " ........ OK"
    else
        echo " !!!!!!!! NOK"
        ERROR=1
    fi
    echo $ERROR  > $TMP_PATH/$DB_NAME.status
    
}

process(){
    dumps
    if [ "$(cat $TMP_PATH/$DB_NAME.status)" = "0" ];
    then
        mv $PERSIT_PATH/$DB_NAME.sql.6 $PERSIT_PATH/$DB_NAME.sql.7 > /dev/null 2>&1
        mv $PERSIT_PATH/$DB_NAME.sql.5 $PERSIT_PATH/$DB_NAME.sql.6 > /dev/null 2>&1
        mv $PERSIT_PATH/$DB_NAME.sql.4 $PERSIT_PATH/$DB_NAME.sql.5 > /dev/null 2>&1
        mv $PERSIT_PATH/$DB_NAME.sql.3 $PERSIT_PATH/$DB_NAME.sql.4 > /dev/null 2>&1
        mv $PERSIT_PATH/$DB_NAME.sql.2 $PERSIT_PATH/$DB_NAME.sql.3 > /dev/null 2>&1
        mv $PERSIT_PATH/$DB_NAME.sql.1 $PERSIT_PATH/$DB_NAME.sql.2 > /dev/null 2>&1
        mv $PERSIT_PATH/$DB_NAME.sql $PERSIT_PATH/$DB_NAME.sql.1 > /dev/null 2>&1
        sleep  $(( $RANDOM % 10 +1 ))m
        mv $TMP_PATH/$DB_NAME.sql $PERSIT_PATH/$DB_NAME.sql > /dev/null 2>&1
        mv $TMP_PATH/$DB_NAME.sql.status $PERSIT_PATH/$DB_NAME.sql.status > /dev/null 2>&1
    fi  
}


next(){
    echo "> Get Next Site"
    COUNTER=$(($COUNTER + 1))
}

is_db_enabled(){
    NAME="DB_"$COUNTER"_NAME"
    DB_NAME=$(eval 'echo $'$NAME)
    if [ -z "$DB_NAME" ];
    then
        return 1
    fi
    
    return 0
}

sleep  $(( $RANDOM % 30 +1 ))m
COUNTER=0
while [ 1 -eq 1 ];
do
    if ! is_db_enabled;
    then
        break
    fi
    process
    next
done